#! Don't hit ctrl+s ! it messes my tabs+spaces with some autoformatting config,
#! I don't know how to get rid of it
#* Docker compose puts Docker containers on the network, so that they can be referenced by name
version: "3.8"
services:
 most-loved-database:
  image: postgres
  env_file:
   - env.development.database
  #   environment:
  #    - POSTGRES_USER=admin
  #    - POSTGRES_PASSWORD=admin
  #    - POSTGRES_DB=most-loved-database
  ports:
   - "5555:5432"
  volumes:
   - "./migrations/:/docker-entrypoint-initdb.d/"
   - "most-loved-database-data:/var/lib/postgresql/data"
 axum-sqlx:
  depends_on:
   - most-loved-database
  build:
   context: .
   dockerfile: Dockferfile
  ports:
   - "3000:3000"
  env_file:
   - .env.development
volumes:
 most-loved-database-data:
